### ISSUE TITLE
Demo

### ISSUE THREAD

**Issue by shen92** [CyxFTS/Hope-Island-Unity#51]
1. UI/scene/state Switch @StephenLiu7 @jialuozh 
UI start - menu - controller - pause (boss clear)? - menu
- [ ] @shen92 find sfx on ui
- [ ] @jialuozh add sfx to ui
- [ ] @StephenLiu7 make telepoter color consistent

2. UI Enhancement
-controller for demo: @CyxFTS @jialuozh 
skills [btn2, btn3, btn4]
- [ ] @shen92 map skills to sound
- [x] @CyxFTS map skills to icon

3. Player dead (SFX Ready)
1) UI prompt: you are dead! @shen92 DESIGN @jialuozh IMPL
2) Back to level 0 scene 1
- [x] player status + UI @CyxFTS 
-health: work
-energy/sta... fake

- [x] 4. Add SFX - SEE Excel @CyxFTS @shen92 @ammydan @XinheY 
player, enemy

- [x] add water @shen92

**Comment by CyxFTS** [comment]
- [ ] Skills Icons for Demo: 1.Sprint 2.Fireball 3.Defense up
